from pathlib import Path
import pandas as pd
import numpy as np

def carrega_ovs():
    caminho_compras = Path('data/vendas')
    lista_ovs = []
    # Percorre todos os arquivos com extensão .xls na pasta de vendas
    for arquivo in caminho_compras.glob('*.xlsx'):
        # Lê todas as planilhas do arquivo, retornando um dicionário
        planilhas = pd.read_excel(arquivo, sheet_name=None)
        # Itera sobre as planilhas e adiciona cada DataFrame à lista
        for nome, df in planilhas.items():
            lista_ovs.append(df)

    # Concatena todos os DataFrames em um único DataFrame consolidado
    df = pd.concat(lista_ovs, ignore_index=True)
    df = ov_general_adjustments(df)
    df = ov_hierarquia_um(df)
    df = ov_hierarquia_dois(df)
    df = ov_hierarquia_tres(df)
    return df


def ov_general_adjustments(df):
    values_to_filter = ['CONTROLS', 'MOTORES INDUSTRIAIS',
       'DRIVES', 'MOTORES COMERCIAIS', 'SOLAR WAU',
       'DRIVES BT', 'CONTROLS CIVIL', 'SOLAR E SMART METER', 'GERADORES',
       'MOTORREDUTOR/REDUTOR', 'SEGURANÇA E SENSORES', 'SERVIÇOS', 'TRANSFORMADORES',
       'SOLAR', 'PAINEIS ESPECIAIS BT', 'NEGOCIOS DIGITAIS', 'CRITICAL POWER',
       'CHAVE DE PARTIDA ESPECIAL', 'MOTORES DE GRANDE PORTE', 
       'EDGE DEVICES E CONECTIVIDADE', 'ENGENHEIRADOS',
       'TOMADAS E INTERRUPTORES', 'REDUTORES INDUSTRIAIS',
       'SISTEMAS AUTOMAÇÃO E ELETRIFICAÇÃO', 'MOTORES APPLIANCE',
       'ESTAÇÕES DE RECARGA VEÍCULOS ELÉTRICOS',
       'ENGENHEIRADOS WDS', 'EQUIPAMENTOS DE ALTA TENSÃO',
       'SMART GRIDS & METERS', 'TURBINA', 'BARRAMENTO BLINDADO BWW', 'Soluções IoT', 
       'DRIVES MT']
    df = df[df['Hier. Produto 1'].isin(values_to_filter)].copy()
    #df.rename(columns={'Cliente': 'Nome do Cliente'}, inplace=True)
    df['Unidade de Negócio'] = df['Unidade de Negócio'].astype('string')
    df['Canal Distribuição'] = df['Canal Distribuição'].astype('string')
    df['ID_Cli'] = df['ID_Cli'].astype('string')
    df['Cliente'] = df['Cliente'].astype('string').str.lower()
    df['Hier. Produto 1'] = df['Hier. Produto 1'].astype('string')
    df['Hier. Produto 2'] = df['Hier. Produto 2'].astype('string')
    df['Hier. Produto 3'] = df['Hier. Produto 3'].astype('string')
    df['Material'] = df['Material'].astype('string')
    df['Produto'] = df['Produto'].astype('string')
    df['Cidade do Cliente'] = df['Cidade do Cliente'].astype('string')
    df['Doc. Vendas'] = df['Doc. Vendas'].astype('string')
    df['Vlr. Entrada'] = df['Vlr. Entrada'] = pd.to_numeric(df['Vlr. Entrada'], errors='coerce')
    df['Qtd. Entrada'] = df['Qtd. Entrada'] = pd.to_numeric(df['Qtd. Entrada'], errors='coerce')
    df['Vlr. Carteira'] = df['Vlr. Carteira'] = pd.to_numeric(df['Vlr. Carteira'], errors='coerce')
    df['Qtd. Carteira'] = pd.to_numeric(df['Qtd. Carteira'], errors='coerce')
    df['Vlr. ROL'] = pd.to_numeric(df['Vlr. ROL'], errors='coerce')
    df['Qtd. ROL'] = pd.to_numeric(df['Qtd. ROL'], errors='coerce')    
    df['Unidade de Negócio'] = df['Unidade de Negócio'].str.replace('WEG Automação', 'WAU')
    df['Unidade de Negócio'] = df['Unidade de Negócio'].str.replace('WEG Digital e Sistemas', 'WDS')
    df['Unidade de Negócio'] = df['Unidade de Negócio'].str.replace('WEG Energia', 'WEN')
    df['Unidade de Negócio'] = df['Unidade de Negócio'].str.replace('WEG Motores Comercial e Appliance', 'WMO-C')
    df['Unidade de Negócio'] = df['Unidade de Negócio'].str.replace('WEG Motores Industrial', 'WMO-I')
    df['Unidade de Negócio'] = df['Unidade de Negócio'].str.replace('WEG Transmissão e Distribuição', 'WTD')
    df.rename(columns={'Unidade de Negócio': 'Unidade'}, inplace=True)
    df['Data Faturamento'] = pd.to_datetime(df['Data Faturamento'], format='%d/%m/%Y', errors='coerce')
    #mat_configurados = ['10000008', '10000151', '10000565', '10000730', '10000740', '10000830', '10000981']
    mat_configurados = ['10000008']
    return df[~df['Material'].isin(mat_configurados)]


def ov_hierarquia_um(df):
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('Soluções IoT', 'DIGITAL SOLUTIONS', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('SOLAR WAU', 'SOLAR', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('SOLAR E SMART METER', 'SOLAR', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('MOTORREDUTOR/REDUTOR', 'MOTORREDUTORES', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('PAINEIS ESPECIAIS BT', 'CHAVES ESPECIAIS', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('CHAVE DE PARTIDA ESPECIAL', 'CHAVES ESPECIAIS', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('MOTORES DE GRANDE PORTE', 'WEN-M', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('ENGENHEIRADOS WDS', 'ENGENHEIRADOS', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('DRIVES BT', 'DRIVES', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('SEGURANÇA E SENSORES', 'SAFETY', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('SISTEMAS AUTOMAÇÃO E ELETRIFICAÇÃO', 'SISTEMAS', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('ESTAÇÕES DE RECARGA VEÍCULOS ELÉTRICOS', 'WEMOB', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('REDUTORES INDUSTRIAIS', 'REDUTORES', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('NEGOCIOS DIGITAIS', 'DIGITAL SOLUTIONS', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('MOTORES INDUSTRIAIS', 'WMO-I', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('MOTORES COMERCIAIS', 'WMO-C', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('BARRAMENTO BLINDADO BWW', 'BWW', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('EQUIPAMENTOS DE ALTA TENSÃO', 'ALTA TENSÃO', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('TOMADAS E INTERRUPTORES', 'BUILDING', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('CONTROLS CIVIL', 'BULDING', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('SMART GRIDS & METERS', 'SMART GRID', regex=False)
    df.loc[:, 'Hier. Produto 1'] = df['Hier. Produto 1'].str.replace('MOTORES APPLIANCE', 'WMO-A', regex=False)
    return df


def ov_hierarquia_dois(df):
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('ACIONAMENTO INVERSOR DE FREQ. PADRÃO', 'INVERSOR', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('INVERSORES DE FREQUÊNCIA ENGENHEIRADOS', 'INVERSOR ENG', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('INVERSORES DE FREQÜÊNCIA ENGENHEIRADOS', 'INVERSOR ENG', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('INVERSORES DE FREQUÊNCIA SERIADOS', 'INVERSOR', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('INVERSOR DE FREQUÊNCIA', 'INVERSOR', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('INVERSOR SOLAR STRING', 'INVERSOR SOLAR', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('INVERSORES DE FREQUÊNCIA SERIADOS', 'INVERSOR', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('BARRAMENTO BLINDADO BWW BT', 'BWW', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('CAPACITORES CFP', 'CAP CFP', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('CAPACITORES MOTOR-RUN', 'CAP MOTOR', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('CAPACITORES PARA ELETRONICA DE POTENCIA', 'CAP EP', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('CHAVE DE PARTIDA ESPECIAL', 'CHAVES ESPECIAIS', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('CHAVE DE PARTIDA SERIADA', 'CHAVES SERIADAS', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('CHAVE FIM DE CURSO', 'FIM DE CURSO', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('CHAVES SECCIONADORAS', 'SECCIONADORA', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('COMANDO E SINALIZAÇÃO', 'COMANDO E SIN', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('DISPOSITIVO PROTETOR DE SURTO', 'SPW', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('DISJUNTOR-MOTOR', 'MPW', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('DISJUNTOR ABERTO', 'ABW', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('DISJUNTOR DE MÉDIA TENSÃO', 'VBW', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('DISJUNTORES EM CAIXA MOLDADA', 'DISJ. CAIXA MOLDADA', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('DISJUNTORES SERIADOS', 'DISJUNTOR SERIADO', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('ENGENHEIRADOS BT WDS', 'ENGENHEIRADOS BT', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('ESTAÇÕES DE RECARGA VEÍCULOS ELÉTRICOS', 'WEMOB', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('EDGE DEVICES', 'GATEWAYS', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('GERADOR FOTOVOLTAICO', 'GER. SOLAR', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('GERENCIAMENTO DE ENERGIA', 'WEM', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace("INTERRUPTOR DIFERENCIAL RESIDUAL(DR'S)", 'DR', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('MEDIDORES DE ENERGIA INTELIGENTES', 'SMW', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('MODULO FOTOVOLTAICO', 'MÓDULOS', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('MOTORES COMERCIAIS', 'WCA1', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('MOTORES DE ALTA TENSÃO', 'WEN-M', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('MOTORES DE BAIXA TENSÃO', 'WEN-M', regex=False)
    
    df.loc[:, 'Hier. Produto 2'] = np.where(df['Unidade'].str.contains('WEN'), 
                                     df['Hier. Produto 2'].str.replace('MOTORES INDUSTRIAIS', 'WEN-M', regex=False),
                                     df['Hier. Produto 2'].str.replace('MOTORES INDUSTRIAIS', 'WMO-I', regex=False)
    )
    
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('MOTORREDUTOR GEREMIA', 'MOTORREDUTORES', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('MOTORREDUTOR NLM', 'MOTORREDUTORES', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('MOTORREDUTOR/REDUTOR', 'MOTORREDUTORES', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('PAINEIS OEMs', 'CHAVES ESPECIAIS', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('PAINEIS VAZIOS - PMW', 'PMW', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('PAINEL TTW01 - CAIXAS', 'TTW', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('PAINEL TTW01 - COLUNAS', 'TTW', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('PARA GRUPOS GERADORES', 'ALTERNADORES', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('PEDAL DE SEGURANÇA', 'PEDAL', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('PLATAFORMA IOT WEGNOLOGY', 'WEGNOLOGY', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('QUADRO DE DISTRIBUIÇÃO', 'QDW', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('RELÉS DE SOBRECARGA TÉRMICOS', 'RELÉS TÉRMICOS', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('RETIFICADORES CUSTOMIZADOS', 'RETIFICADOR', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('RETIFICADORES SERIADOS', 'RETIFICADOR', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SENSORES E SISTEMAS DE VISÃO', 'SISTEMAS DE VISÃO', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SERVIÇO DE ASSISTÊNCIA TÉCNICA', 'ASTEC', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SERVIÇOS DE ENGENHARIA', 'ENGENHARIA', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SERVIÇOS DIVERSOS', 'DIVERSOS', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SERVIÇO DE REFORMA', 'REFORMA', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SERVIÇO DE TREINAMENTO', 'TREINAMENTO', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SERVIÇOS ESPECIALIZADOS WDI', 'WDI', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SISTEMAS BT WDS', 'SISTEMAS WDS', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SISTEMAS DE IDENTIFICAÇÃO WEG', 'IDENTIFICAÇÃO BTW', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SOFT-STARTERS SERIADAS', 'SOFT-STARTER', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SOFT-STARTERS BT', 'SOFT-STARTER', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SOFT-STARTERS ENGENHEIRADAS', 'SOFT-STARTER ENG', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('SWITCHES INDUSTRIAIS', 'SWITCHES', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('TRANSFORMADOR A ÓLEO PEDESTAL', 'PEDESTAL', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('TRANSFORMADORES A ÓLEO DISTRIBUIÇÃO', 'DISTRIBUIÇÃO', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('TRANSFORMADORES A ÓLEO FORÇA', 'FORÇA', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('TRANSFORMADORES A ÓLEO MEDIA FORÇA I', 'MEIA FORÇA', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('TRANSFORMADORES A ÓLEO MEDIA FORÇA II', 'MEIA FORÇA', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('TRANSFORMADORES A ÓLEO MEIA FORÇA', 'MEIA FORÇA', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('TRANSFORMADORES SECO', 'SECO', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('WCG20 / WG20', 'WCG20', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('WEG MOTION FLEET MANAGEMENT', 'WMFM', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('WEG MOTOR SCAN', 'MOTOR SCAN', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('WEG SCAN', 'WSCAN', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('WEG SMART MACHINE', 'WSM', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('WEGNOLOGY EDGE SUITE', 'WEGNOLOGY', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('WEGSCAN', 'WSCAN', regex=False)
    df.loc[:, 'Hier. Produto 2'] = df['Hier. Produto 2'].str.replace('WEGSCAN 1000', 'WSCAN 1000', regex=False)
    return df

def ov_hierarquia_tres(df):
    df['Hier. Produto 3'] = df['Hier. Produto 3'].apply(lambda x: 'ACESSÓRIOS' if isinstance(x, str) and 'ACESS' in x else x)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('CHAVE DE PARTIDA CX. TERMOPLÁSTICA', 'PDW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W22 RURAL TEFC', 'W22 RURAL', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('MPW25/40', 'MPW40', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('MPW12/16/18', 'MPW18', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('FUSÍVEL NH ULTRARRÁPIDO', 'aR', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('CONTATORES AUXILIARES', 'CAW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('SERVIÇO DE REFORMA', 'REFORMA', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RS GERAL FHP ODP MONO (ANTIGO)', 'ODP (ANTIGO)', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('SACA FUSÍVEL - FSW', 'FSW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('CONTATOR CAPACITOR CWMC', 'CWMC', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('CONJUNTOS CEW', 'CEW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('FUSÍVEL NH RETARDADO', 'gG', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('CONJUNTOS CSW', 'CSW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('HIDROGERADORES - GH20', 'GH20', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TURBOGERADORES ST41', 'ST41', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W22Xdb À PROVA DE EXPLOSÃO', 'W22X-db', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('SINALEIROS CEW', 'SIN CEW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TRANSFORMADORES A ÓLEO INDUSTRIAL', 'ÓLEO INDUSTRIAL', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('WCG20 VERTIMAX / WG20 F', 'VERTIMAX', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('HIDROGERADORES - SH11', 'SH11', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RS AVIÁRIO', 'AVIÁRIO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TRANSFORMADORES SECO INDUSTRIAL', 'SECO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('HIDROGERADORES - GH11', 'GH11', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('CHAVE DE PARTIDA CX. METÁLICA ESPECIAL', 'CHAVE ESPECIAL', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('MOTORREDUTOR/REDUTOR', 'MOTORREDUTOR', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('SL - INDUTIVOS', 'INDUTIVOS', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('HIDROGERADORES S', 'GH-S', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('MOTORES INDUSTRIAIS', 'WMO-I', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('WMFM MANGMT MOTOR', 'WMFM', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('BOTÕES CSW', 'BOT CSW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('PSS24 - PADRAO', 'PSS24', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RELÉS DE NÍVEL', 'RNW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('FUSÍVEL D RETARDADO', 'D', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('CONTATOR CAPACITOR CWBC', 'CWBC', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W21Xdb À PROVA DE EXPLOSÃO', 'W21X-DB', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TURBOGERADORES S', 'TG-S', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RS GERAL FHP ODP MONO', 'ODP MONO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W22 MOTOFREIO', 'MOTOFREIO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('FUSIVEL FLUSH END', 'FLUSH END', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('ASSINATURA SAAS WEG SMART MACHINE', 'WSM-SIG', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('MODULO FOTOVOLTAICO', 'MÓDULO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('SC - CAPACITIVOS', 'CAPACITIVOS', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W22Xec SEGURANÇA AUMENTADA (NÃO ACENDÍVE', 'W22X-ec', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('CONTROLADOR AUTOMÁTICO', 'PFW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('ROTATIVA PORTA FUSIVEL - RFW', 'RFW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TRANSFORMADOR A ÓLEO DE POTÊNCIA', 'ÓLEO POTENCIA', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W22Xtb DIP', 'DIP W22X-tb', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('SERVIÇO DE ENGENHARIA', 'ENGENHARIA', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('COMUTADORES CSW', 'COMT CSW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TRANSFORMADOR A ÓLEO INDUSTRIAL', 'ÓLEO INDUSTRIAL', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W22 MOTOR PARA REDUTOR TIPO 1', 'TIPO 1', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('WEG MOTOR SCAN COM SUBSCRIÇÃO', 'MOTOR SCAN', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('MOTORES DE ALTA TENSÃO - H', 'WEN-H', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('IHM MT', 'IHM', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('WCG20 COAXIAL / WG20 C', 'COAXIAL', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('BOTÕES CEW', 'BOT CEW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TRANSFORMADORES A ÓLEO DE POTÊNCIA', 'ÓLEO POTENCIA', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('BOTÕES CSW-M', 'BOT CSW-M', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('WCG20 CONIMAX / WG20 K', 'CONIMAX', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RS GERAL FHP ODP TRIF (ANTIGO)', 'ODP 3F ANTIGO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RS GERAL FHP TEFC MONO (ANTIGO)', 'MONO ANTIGO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('MOTORES DE ALTA TENSÃO - M', 'WEN-M', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TRANSFORMADORES A ÓLEO DE DISTRIBUIÇÃO', 'DISTRIBUIÇÃO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TRANSFORMADORES SECO PARA RETIFICADOR', 'SECO RETF', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('GERADORES PARA GRUPOS GERADORES', 'ALTERNADOR', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W22Xec WELL SEGURANÇA AUMENTADA', 'WELL EX-ec', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('JET PUMP BOMBA/FILTRO', 'JET PUMP', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W01 FHP ODP TRIF', 'W01 TRIF', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TRANSFORMADORES A ÓLEO TIPO AUTOTRAFO', 'AUTOTRAFO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('COMUTADORES CEW', 'COMT CEW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RECTIFIER', 'RETIFICADOR', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('AFW11 CUSTOMIZADO', 'AFW11', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('COMUTADORES CSW-M', 'COMT CSW-M', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('GATEWAY MOTOR SCAN', 'GATEWAY', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TRANSFORMADORES SECO', 'SECO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('BOMBA COMBUSTÍVEL FERRO', 'BB COMBUSTIVEL FF', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('MINI FECHADO', 'MINI FECHADO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W22 BOMBA MONOBLOCO JM/JP', 'JM/JP', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('WEM CLOUD SAAS', 'WEM', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('WSDAL - DUPLA ABERTURA LATERAL', 'WSDAL', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('IDENTIFICADOR DE BORNES', 'ID BORNES', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RS GERAL FHP TEFC MONO', 'MONO FECHADO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('AC RESIDENCIAL JANELA', 'AC JANELA', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('PSS24W - METALICA', 'PSS24W METAL', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('SWITCHES ETHERNET SWU', 'SWITCH SWU', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('AFW11M G2 CUSTOMIZADO', 'AFW11M G2', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('Sistema Integrado de Distribuição (SID)', 'SID', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TURBINA FRANCIS SIMPLES EIXO HORIZONTAL', 'TURBINA FRANCIS', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('SINALEIROS CSW', 'SIN CSW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TRANSFORMADORES A ÓLEO PARA FORNO', 'ÓLEO FORNO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('QUADROS DE COMANDO - PNW', 'PNW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('WEG DRIVE SCAN SEM ASSINATURA', 'DRIVE SCAN NO SIGN', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W21 MOTOFREIO AL', 'W21 AL COM FREIO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('BOMBA COMBUSTÍVEL CHAPA', 'BB COMBUSTIVEL CHAPA', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('ON PREMISE LICENCA', 'LICENÇA WEN', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RELÉS DE MULTI-FUNÇÕES', 'ERWM', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RS WJET PUMP ODP (ANTIGO)', 'JET PUMP ANTIGO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RTDW CUSTOMIZADO (NÃO UTILIZAR)', 'RTDW*', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('BANCO DE BATERIAS RETIFICADORES', 'BATERIAS RETIF', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RS GERAL FHP ODP TRIF', 'ODP TRIF', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('SERVIÇOS DIVERSOS', 'DIVERSOS', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('SM - MAGNÉTICOS', 'MAGNÉTICOS', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('MOTORES DE ALTA TENSÃO - M MINING', 'WEN-MINING', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('QUADROS DE COMANDO - PNW WDS', 'PNW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RP- IRRIGATION (60 AND 61)', 'REDUTOR RODA PIVÔ', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('WEGNOLOGY DEVELOPER PAAS', 'WEGNOLOGY', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('WEGNOLOGY GENERIC', 'WEGNOLOGY', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('SMW CONCESSIONÁRIA', 'SMW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('HMI ENG&RUNTIME WES', 'WES', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('HIDROGERADORES - SH1', 'SH1', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('AFW11 PADRÃO', 'AFW11', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W22 MOTOFREIO PARA REDUTOR TIPO 1', 'W22 TIPO 1 COM FREIO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('COMUTADORAS ROTATIVA', 'MSW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('AFW11C PADRÃO', 'AFW11C', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TRANSFORMADOR A ÓLEO PEDESTAL', 'PEDESTAL', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('MOTORES COMERCIAIS', 'WMO-C', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('RTDW CUSTOMIZADO', 'RTDW', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('BOMBA COMBUSTÍVEL CH', 'BB COMBUSTIVEL CH', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('TRANSFORMADORES A ÓLEO MEIA FORÇA', 'ÓLEO MEIA FORÇA', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('SD - ÓPTICOS DIFUSOS', 'OPT DIFUSO', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('W22 RURAL FARM DUTY', 'W22 RURAL', regex=False)
    df.loc[:, 'Hier. Produto 3'] = df['Hier. Produto 3'].str.replace('AC RESIDENCIAL SPLIT', 'AC SPLIT', regex=False)
    return df